spring.application.name=${APP_NAME:tvmaze-middleware-api}
server.port=${SERVER_PORT:8080}
tvmaze.base-url=${TVMAZE_BASE_URL:https://api.tvmaze.com}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://tvmaze_user:tvmaze090926@tvmaze.rxy1kjl.mongodb.net/tvmaze?appName=tvmaze}